name: Restful Booker Env
values:
  - key: baseUrl
    value: ''
  - key: username
    value: ''
  - key: password
    value: ''
  - key: token
    value: ''
  - key: bookingId
    value: ''
  - key: checkinDate
    value: ''
  - key: checkoutDate
    value: ''
  - key: lastname
    value: ''
color: 0
